.nr PS 12p
.nr LL 6.5i
.TL
Chemical Structures
.AU
Mitch Feigenbaum
.SH
Butane (C\*{4\*}H\*{10\*})
.cstart
H
bond right
C
bond up
H
bond down from C
H
bond right from C
C
bond up
H
bond down from C
H
bond right from C
C
bond up
H
bond down from C
H
bond right from C
C
bond up
H
bond down from C
H
bond right from C
H
.cend
.SH
The Superior Propane (C\*{3\*}H\*{8\*})
.cstart
H
bond se
C
bond sw
H
bond down from C
H
bond ne from C
C
bond nw
H
bond ne from C
H
bond se from C
C
bond down from C
H
bond se from C
H
bond ne from C
H
.cend
