#define AND	&&
#define OR	||
#define BEGIN	{
#define END	;}
#define DO	){
#define OD	;}
#define IF	if(
#define THEN	){
#define ELSE	;}else{
#define FI	;}
#define FOR	for(
#define WHILE	while(
#define SWITCH	switch(
#define CASE	){
#define IN	;case
#define OUT	;default:
#define ESAC	;}
#define CHAR	char
#define STRING	char*
#define INT	int
#define FLOAT	float
#define VOID	void

