.TL
D'Morgan's Laws
.EQ
define let %roman {"let "}%
matrix {
lcol {
{let x~\[mo]~\[no] left ( A\[AN]B right )}
above
{x~\[nm]~A\[AN]B}
above
{x~\[mo]~\[no]A~\[OR]~x~\[mo]~\[no]B}
above
{\[3d]~\[no] left ( A\[AN]B right ) = ~\[no]A\[OR]\[no]B}
}
rcol {
{let x~\[mo]~\[no] left ( A\[OR]B right )}
above
{x~\[nm]~A\[OR]B}
above
{x~\[mo]~\[no]A~\[AN]~x~\[mo]~\[no]B}
above
{\[3d]~\[no] left ( A\[OR]B right ) = ~\[no]A\[AN]\[no]B}
}
}
.EN
